export const FETCH_SHOPPING_LIST_ITEMS = 'FETCH_SHOPPING_LIST_ITEMS';

// web socket actions
export const SHOPPING_LIST_ITEM_CREATED = 'SHOPPING_LIST_ITEM_CREATED';
export const SHOPPING_LIST_ITEM_DELETED = "SHOPPING_LIST_ITEM_DELETED";
export const SHOPPING_LIST_ITEM_UPDATED = "SHOPPING_LIST_ITEM_UPDATED";