management.endpoints.web.exposure.include=prometheus,health,info
management.metrics.tags.application=shopping-list

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://localhost:5432/food-planner
spring.datasource.username=food-planner
spring.datasource.password=food-planner
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

ingredient-breakdown.api.url=http://ingredient-extractor:5001/breakdown_ingredient