## PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${POSTGRES_LOCATION:jdbc:postgresql://localhost:5432/food-planner}
spring.datasource.username=food-planner
spring.datasource.password=food-planner
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

