name: Build

on:
  push:
    branches:
      "*"
    tags:
      "*"
  workflow_dispatch:
  workflow_run:
    workflows:
      - tagging
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Set DOCKER_TAG_NAME
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          if [ $GITHUB_EVENT_NAME = "workflow_run" ]; then
            git fetch --tags
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            git checkout $latest_tag
            echo "DOCKER_TAG_NAME=$latest_tag" >> $GITHUB_ENV
          elif [[ $BRANCH_NAME == dependabot* ]]; then
            echo "DOCKER_TAG_NAME=dependabot-$(date --utc +%s)" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - run: echo "DOCKER_TAG_NAME is ${{ env.DOCKER_TAG_NAME }}"
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw && chmod +x build.sh
      - name: Build with Maven
        run: ./mvnw clean install
      - name: Build frontend
        run: cd frontend && npm install && npm run build
      - name: Build container
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG_NAME: ${{ env.DOCKER_TAG_NAME }}
        run: ./build.sh $DOCKER_USERNAME $DOCKER_PASSWORD $TAG_NAME
